// Tougaard background — JS twin of fitting.py's tougaard_background.
//
// The function lives inline in templates/index.html; extract its source and
// evaluate it so these tests exercise the exact shipped code. Pins the
// 2026-07-04 fix (mirrored from the backend, see
// tests/test_tougaard_background.py):
//   1. Universal cross-section constant C = 1643 eV² (was shipped squared:
//      1643*1643). Kernel K(T) = B·T/(C+T²)² peaks at sqrt(C/3) ≈ 23.4 eV.
//      S. Tougaard, Surf. Interface Anal. 11, 453 (1988).
//   2. Order-robustness: the one-sided loss sum needs a descending-BE grid;
//      ascending input is normalized internally and flipped back.
//   3. Amplitude anchored to the measured intensity at the HIGH-BE edge
//      (the old "trailing endpoint" rescale was degenerate: K(0)=0 forced
//      the zero-guard, multiplying by raw trailing counts instead).

const { test } = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');

const html = fs.readFileSync(
  path.join(__dirname, '../../templates/index.html'), 'utf8');
const match = html.match(/function tougaardBackground\([\s\S]*?\n\}/);
assert.ok(match, 'tougaardBackground not found in templates/index.html');
const tougaardBackground = eval('(' + match[0] + ')');

function syntheticSpectrum() {
  // Same C 1s-like region as the Python tests: descending BE, dx = 0.1 eV.
  const be = [], intensity = [];
  for (let i = 0; i <= 150; i++) {
    const x = 295.0 - 0.1 * i;
    be.push(x);
    intensity.push(
      100.0
      + 5000.0 * Math.exp(-0.5 * Math.pow((x - 287.0) / 0.8, 2))
      + 400.0 / (1.0 + Math.exp(-(287.0 - x)))
    );
  }
  return { be, intensity };
}

test('loss-kernel response peaks ~23.4 eV above a delta-like peak', () => {
  const n = 1001;
  const be = [], intensity = [];
  for (let i = 0; i < n; i++) {
    be.push(100.0 - 0.1 * i);      // descending 100 → 0 eV
    intensity.push(1e-9);          // pedestal keeps the amplitude anchor finite
  }
  const spikeIdx = 800;            // be = 20.0 eV
  intensity[spikeIdx] = 1e6;

  const bg = tougaardBackground(be, intensity);

  let maxV = -Infinity, maxX = NaN;
  for (let i = 0; i < spikeIdx; i++) {   // high-BE side: traces K(be − 20)
    if (bg[i] > maxV) { maxV = bg[i]; maxX = be[i]; }
  }
  const expected = 20.0 + Math.sqrt(1643.0 / 3.0);  // ≈ 43.4 eV
  assert.ok(Math.abs(maxX - expected) <= 0.25,
    `kernel response peaks at ${maxX.toFixed(2)} eV, expected ~${expected.toFixed(2)}; ` +
    'a peak near 100 eV means the squared constant (1643*1643) is back');
});

test('ascending and descending BE input give the identical background', () => {
  const { be, intensity } = syntheticSpectrum();
  const bgDesc = tougaardBackground(be, intensity);
  const bgAsc = tougaardBackground([...be].reverse(), [...intensity].reverse());
  bgAsc.reverse();
  for (let i = 0; i < be.length; i++) {
    assert.strictEqual(bgDesc[i], bgAsc[i],
      `order-dependent output at index ${i}: ${bgDesc[i]} vs ${bgAsc[i]}`);
  }
});

test('background anchored to the data at the high-BE edge, zero at low-BE edge', () => {
  const { be, intensity } = syntheticSpectrum();
  const bg = tougaardBackground(be, intensity);
  const rel = Math.abs(bg[0] - intensity[0]) / intensity[0];
  assert.ok(rel < 1e-12,
    `high-BE-edge anchor broken: bg[0] = ${bg[0]}, data = ${intensity[0]}`);
  assert.strictEqual(bg[bg.length - 1], 0);
});

test('agrees with the backend implementation (fitting.py) on the same spectrum', () => {
  // Expected values generated by the CORRECTED backend on 2026-07-04:
  //   venv/bin/python - <<'EOF'
  //   import numpy as np; from fitting import tougaard_background
  //   x = np.linspace(295.0, 280.0, 151)
  //   y = (100.0 + 5000.0*np.exp(-0.5*((x-287.0)/0.8)**2)
  //        + 400.0/(1.0+np.exp(-(287.0-x))))
  //   bg = tougaard_background(x, y)
  //   print([float(bg[i]) for i in (0, 30, 75, 110, 149, 150)])
  //   EOF
  // Regenerate with that snippet if the backend numerics change for a
  // reviewed reason. Tolerance 1e-9 relative: np.convolve vs the JS loop
  // differ only by floating-point summation order.
  const expected = {
    0: 100.1341400521866,
    30: 68.83942567577668,
    75: 17.647993800534383,
    110: 3.6432237281257964,
    149: 0.0045035685195542186,
    150: 0.0,
  };
  const { be, intensity } = syntheticSpectrum();
  const bg = tougaardBackground(be, intensity);
  for (const [idx, want] of Object.entries(expected)) {
    const got = bg[Number(idx)];
    const tol = want === 0 ? 1e-15 : Math.abs(want) * 1e-9;
    assert.ok(Math.abs(got - want) <= tol,
      `backend/frontend disagree at index ${idx}: js ${got} vs python ${want}`);
  }
});
