#!/usr/bin/env python
"""Generate docs/autofit/fit-physics-coverage-report.md — the per-value review
table for the machine-tier / fit-physics coverage expansion (the audit surface
Skye hand-verifies against NIST before trusting any value).

Pure reporting from committed files (elements-machine.json + provenance +
skipped + fit-physics.json). Re-run after regeneration; never hand-edit.
"""
import json
import os
from collections import Counter

REPO = os.path.join(os.path.dirname(__file__), "..")
DATA = os.path.join(REPO, "data", "xps")
OUT = os.path.join(REPO, "docs", "autofit", "fit-physics-coverage-report.md")


def load(name):
    with open(os.path.join(DATA, name)) as f:
        return json.load(f)


def main():
    machine = load("elements-machine.json")
    prov = {p["id"]: p for p in load("elements-machine.provenance.json")["transitions"]}
    skipped = load("elements-machine.skipped.json")
    fitphys = load("fit-physics.json")

    trans = [(el, t) for el in machine["elements"]
             for fam in el["families"] for t in fam["transitions"]]

    lines = [
        "# Element fit-physics coverage report (auto-generated)",
        "",
        "*Generated by scripts/gen_coverage_report.py from the committed data "
        "files. Every machine value below is UNVERIFIED-until-reviewed: "
        "hand-check against the archived NIST snapshot (provenance URL) "
        "before trusting.*",
        "",
        f"- machine-tier transitions: **{len(trans)}** across "
        f"**{len(machine['elements'])}** elements",
        f"- fit-physics entries: **{len(fitphys['entries'])}**",
        f"- skipped (audit log): **{skipped['skipped_count']}** — "
        + ", ".join(f"{k} {v}" for k, v in sorted(Counter(
            s["reason"] for s in skipped["transitions"]).items())),
        "",
        "## Machine-tier per-value review table",
        "",
        "| id | BE (eV) | NIST ref | region (eV) | acquisition | snapshot | x-checked |",
        "|---|---|---|---|---|---|---|",
    ]
    for el, t in sorted(trans, key=lambda et: (et[0]["z"], et[1]["orbital"])):
        p = prov[t["id"]]
        ns = p["nominal_source"]
        acq = "expansion" if p.get("acquisition") else "stage9-dual"
        snap = ns.get("archive_snapshot_timestamp", "—")
        xc = ("✓" if p.get("agent_cross_checked")
              else ("dual" if p.get("dual_extraction_corroborated") else "✗"))
        reg = t["expected_region_ev"]
        lines.append(
            f"| {t['id']} | {t['nominal_be_ev']:g} | {ns['nist_reference_code']} "
            f"| {reg['min']:g}–{reg['max']:g} | {acq} | {snap} | {xc} |")

    lines += [
        "",
        "## Fit-physics status mix",
        "",
    ]
    st = Counter(e["status"] for e in fitphys["entries"].values())
    for k, v in sorted(st.items()):
        lines.append(f"- {k}: {v}")
    n_so = sum(1 for e in fitphys["entries"].values() if "spin_orbit" in e)
    n_stat = sum(1 for e in fitphys["entries"].values()
                 if "statistical_area_ratio" in e)
    lines += [
        f"- entries with sourced spin-orbit: {n_so}",
        f"- entries with 2j+1 statistical ratio (arithmetic): {n_stat}",
        "",
        "No value in these tables comes from model memory; sources are the "
        "archived NIST SRD-20 snapshots (sha256-pinned in "
        "`elements-machine.provenance.json`), the already-sourced data/xps "
        "tiers, pure 2j+1 arithmetic, or DOI-cited literature seeds.",
    ]
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(trans)} machine transitions)")


if __name__ == "__main__":
    main()
