#!/usr/bin/env python
"""Summarize docs/autofit/inventory/bayesian_real_validation_runs.jsonl into
docs/autofit/bayesian-real-validation.md (cross-method winner agreement,
seed/tunable stability, free-energy spreads, ESS honesty, params vs expert).

Pure reporting — no fits are run; the JSONL is the evidence of record.
"""
import json
import os
from collections import defaultdict

REPO = os.path.join(os.path.dirname(__file__), "..")
SRC = os.path.join(REPO, "docs", "autofit", "inventory",
                   "bayesian_real_validation_runs.jsonl")
OUT = os.path.join(REPO, "docs", "autofit", "bayesian-real-validation.md")


def load():
    recs = [json.loads(l) for l in open(SRC)]
    by_anchor = defaultdict(list)
    for r in recs:
        by_anchor[r["anchor"]].append(r)
    return by_anchor


def fnum(v, nd=2):
    return "—" if v is None else f"{v:.{nd}f}"


def main():
    by_anchor = load()
    lines = [
        "# Bayesian exchange-MC — real-data validation (auto-generated)",
        "",
        f"*Generated by scripts/summarize_bayesian_validation.py from "
        f"{os.path.relpath(SRC, REPO)} — do not hand-edit; re-run the script.*",
        "",
        "Anchors and configurations per scripts/run_bayesian_real_validation.py; "
        "IC = the engine's information-criterion method at gate options; "
        "Bayes runs at the default sampler settings (2 seeds) plus a one-factor "
        "sweep of the UNVERIFIED sampler tunables on the cheap anchors.",
        "",
        "Takeaways (2026-07-03 battery, fixed method with split-half F error "
        "bars + UNRESOLVED-selection warning):",
        "",
        "- **Cl 2p / B 1s: cross-method agreement at every setting** — the "
        "Bayesian winner matches IC's (mod +bfix) for both seeds and every "
        "tunable variation; ΔF decisive (Cl 2p ~47, B 1s 113–148).",
        "- **U 4f: honestly UNRESOLVED at the default budget** — U1b vs U2 "
        "flip winners across seeds (ΔF ≈ 3–6 vs seed spread ≈ 5); the "
        "warning machinery + `seed_replicates` option now flag this "
        "(env-gated pin: tests/autofit/test_bayesian_u4f_unresolved_gate.py). "
        "IC decisively prefers U2 (ΔBIC* = 59). Tuned run (16 replicas / "
        "4000 sweeps): docs/autofit/inventory/bayesian_u4f_tuned_run.jsonl.",
        "- **Tuning evidence**: winner selection is insensitive to all swept "
        "sampler tunables on the resolved anchors; min-ESS improves most "
        "with n_replicas (B 1s: 4→13 at 8→16 replicas), far less with "
        "n_sweeps; boundary-piled chains (Cl 2p ratio at its 0.55 cap) "
        "keep ESS low by construction and correctly fire the CI honesty "
        "warning. Sampler tunables remain UNVERIFIED defaults — validated "
        "as adequate for model selection on these anchors, NOT tuned "
        "constants.",
        "- Records predate `free_energy_mc_error`/replicate fields where "
        "noted; at seed_replicates=1 the MC error equals the split-half "
        "error by definition.",
        "",
    ]

    for anchor in sorted(by_anchor):
        recs = by_anchor[anchor]
        ic = [r for r in recs if r["method"] == "ic_model_comparison"]
        bayes = [r for r in recs if r["method"] == "bayesian_exchange_mc"]
        lines.append(f"## {anchor}")
        lines.append("")
        if ic:
            r = ic[0]
            expert_chi = (r.get("expert") or {}).get("chi_reduced")
            win = next((c for c in (r.get("candidates") or [])
                        if c.get("name") == r.get("winner", "").replace("+bfix", "")
                        or c.get("name") == r.get("winner")), None)
            lines.append(
                f"- **IC**: winner `{r.get('winner')}`"
                + (f", conditional={r.get('conditional')}" if r.get("conditional") is not None else "")
                + (f", χ²ᵣ {fnum(win.get('reduced_chi_sq'))}" if win else "")
                + (f" (expert {fnum(expert_chi)})" if expert_chi else "")
                + f", {r.get('runtime_s')}s")
        winners = sorted({r.get("winner") for r in bayes})
        agree = "AGREE" if ic and len(winners) == 1 and winners[0] == \
            (ic[0].get("winner") or "").replace("+bfix", "") else \
            ("stable" if len(winners) == 1 else "UNSTABLE")
        lines.append(f"- **Bayes winners across {len(bayes)} runs**: "
                     f"{winners} — {agree} "
                     f"{'(vs IC modulo +bfix)' if agree == 'AGREE' else ''}")
        lines.append("")
        lines.append("| config | seed | winner | ΔF to 2nd | ±F err | σ̂ | swap acc | min ESS | CI warn | sel warn | t(s) |")
        lines.append("|---|---|---|---|---|---|---|---|---|---|---|")
        for r in sorted(bayes, key=lambda r: (json.dumps(r["config"], sort_keys=True), r["seed"])):
            cands = [c for c in (r.get("candidates") or []) if "free_energy" in (c or {})]
            cands.sort(key=lambda c: c["free_energy"])
            dF = (cands[1]["free_energy"] - cands[0]["free_energy"]) if len(cands) > 1 else None
            wc = cands[0] if cands else {}
            cfg = {k: v for k, v in r["config"].items()
                   if v != {"n_replicas": 12, "beta_min": 1e-4, "n_sweeps": 1500,
                            "burn_fraction": 0.5, "exchange_every": 5}.get(k)}
            # selection warning: records predating the split-half machinery
            # have no field (shown 'n/a'); newer records show YES/–
            sel = r.get("selection_warning",
                        (r.get("analysis") or {}).get("model_selection_warning", "n/a")
                        if "analysis" in r else "n/a")
            sel_disp = "n/a" if sel == "n/a" else ("YES" if sel else "–")
            lines.append(
                f"| {json.dumps(cfg) if cfg else 'default'} | {r['seed']} "
                f"| {r.get('winner')} | {fnum(dF, 1)} "
                f"| {fnum(wc.get('free_energy_split_half_error'), 1) if isinstance(wc.get('free_energy_split_half_error'), (int, float)) else 'n/a'} "
                f"| {fnum(r.get('sigma_hat'), 1)} "
                f"| {fnum(wc.get('swap_acceptance'), 2)} | {fnum(wc.get('min_effective_sample_size'), 1)} "
                f"| {'YES' if wc.get('ci_reliability_warning') else '–'} | {sel_disp} | {r.get('runtime_s')} |")
        lines.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
