#!/usr/bin/env python
"""Summarize docs/autofit/inventory/sensitivity_sweeps.jsonl into
docs/autofit/sensitivity-sweeps.md — the spec-§9 sensitivity evidence for
the UNVERIFIED / CONDITIONAL pipeline constants.

Pure reporting; the JSONL is the evidence of record. Re-run after sweeps."""
import json
import os
from collections import defaultdict

REPO = os.path.join(os.path.dirname(__file__), "..")
SRC = os.path.join(REPO, "docs", "autofit", "inventory", "sensitivity_sweeps.jsonl")
OUT = os.path.join(REPO, "docs", "autofit", "sensitivity-sweeps.md")


def main():
    recs = [json.loads(l) for l in open(SRC)]
    base = {r["anchor"]: r["result"] for r in recs if r["constant"] == "<default>"}
    # proposal group's baseline is its own record
    prop_base = {r["anchor"]: r["result"] for r in recs
                 if r["constant"] == "<default+proposal_on>"}

    by_group = defaultdict(list)
    for r in recs:
        by_group[r["group"]].append(r)

    lines = [
        "# Sensitivity sweeps — UNVERIFIED / CONDITIONAL constants (auto-generated)",
        "",
        "*Generated by scripts/summarize_sensitivity.py; evidence of record in "
        "docs/autofit/inventory/sensitivity_sweeps.jsonl. One-factor-at-a-time "
        "around the engine defaults on the real region anchors; every run is "
        "IC at gate options.*",
        "",
        "**Verdict rule:** a constant is 'insensitive on the labeled anchors' "
        "when winner AND conditional status match the default run at every "
        "swept value. Insensitivity here is evidence for keeping defaults, "
        "NOT literature verification — flags stay until a cited basis exists "
        "(spec §9).",
        "",
    ]

    for group in sorted(by_group):
        rows = [r for r in by_group[group] if not r["constant"].startswith("<default")]
        if not rows:
            continue
        lines.append(f"## group: {group}")
        lines.append("")
        lines.append("| anchor | constant | value | winner | cond | χ²ᵣ | Δ vs default |")
        lines.append("|---|---|---|---|---|---|---|")
        for r in sorted(rows, key=lambda r: (r["anchor"], r["constant"], str(r["value"]))):
            b = (prop_base if group == "proposal" else base).get(r["anchor"], {})
            res = r["result"]
            same = (res["winner"] == b.get("winner")
                    and res["conditional"] == b.get("conditional"))
            delta = "same" if same else "**CHANGED**"
            chi = res.get("winner_chi_r")
            lines.append(
                f"| {r['anchor']} | {r['constant']} | {r['value']} "
                f"| {res['winner']} | {res['conditional']} "
                f"| {chi and round(chi, 3)} | {delta} |")
        lines.append("")

    # headline: constants whose sweep changed any conclusion
    changed = defaultdict(list)
    for r in recs:
        if r["constant"].startswith("<default"):
            continue
        b = (prop_base if r["group"] == "proposal" else base).get(r["anchor"], {})
        res = r["result"]
        if res["winner"] != b.get("winner") or res["conditional"] != b.get("conditional"):
            changed[r["constant"]].append((r["anchor"], r["value"]))
    lines.append("## Headline")
    lines.append("")
    if changed:
        for const, hits in sorted(changed.items()):
            lines.append(f"- **{const}** changes the conclusion at: {hits}")
    else:
        lines.append("- No swept constant changed any anchor's conclusion.")
    lines.append("")
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(recs)} runs)")


if __name__ == "__main__":
    main()
